# Configurações de PRODUÇÃO
# ATENÇÃO: não versione este arquivo com credenciais reais em um repositório público.

server.port=8090
server.servlet.context-path=/tv-wall

app.db.schema=prisma

spring.datasource.url=jdbc:postgresql://localhost:5432/prismadb?currentSchema=${app.db.schema}
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=${app.db.schema}
